set nocompatible
set backspace=indent,eol,start
set autoindent
"set editing-mode vi
set clipboard=unnamed

set showmatch

filetype indent on

syntax enable

set number

" Python Support
autocmd Filetype python setlocal ts=4 sw=4 colorcolumn=80
set tabstop=4
set expandtab
let python_highlight_all=1
let g:syntastic_python_checkers=[]


" Javascript and Typescript support
autocmd Filetype json setlocal ts=2 sw=2
autocmd Filetype javascript setlocal ts=2 sw=2 colorcolumn=120
autocmd Filetype Typescript setlocal ts=2 sw=2 sts=4 colorcolumn=120
let g:syntastic_typescript_tsc_fname = ''
let g:syntastic_typescript_checkers=[]

" RST
autocmd FileType rst setlocal expandtab sw=4 ts=4 colorcolumn=80
let g:syntastic_rst_checkers=['sphinx']


" Enable Folding

set foldmethod=indent
set foldlevel=99

" Colorschemes
set background=dark

" Shift tab to detab
vnoremap <S-Tab> <<
vnoremap <Tab> >>
inoremap <S-Tab> hello 
"inoremap <S-Tab> <C-d>
        
" System clipboard

set clipboard=unnamed

" VIM in the Shell
" Syntastic settings

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let syntastic_mode_map = {
            \"passive_filetypes": ['html', 'typescript']
            \}


" Vim Airline

set laststatus=2

" NerdTree
let NERDTreeIgnore = ['\.pyc$', '\.swp$', '.git', '.idea', 'node_modules', '.cache', '.pants.d', '.pids', '.pytest_cache', '.DS_store', '.pants.workdir.file_lock', '.DS_Store']
:map <leader>n :NERDTree<enter>
let NERDTreeShowHidden = 1

" NerdTree Commentator

:map <C-\> <Leader>cc

call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle'}
Plug 'tpope/vim-git'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'altercation/vim-colors-solarized'
Plug 'scrooloose/syntastic'
Plug 'vim-airline/vim-airline'
Plug 'jmcantrell/vim-virtualenv'
Plug 'Valloric/YouCompleteMe'
Plug 'nvie/vim-flake8'
Plug 'vim-scripts/indentpython.vim'
Plug 'Rykka/riv.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'pangloss/vim-javascript'
Plug 'leafgarland/typescript-vim'
Plug 'editorconfig/editorconfig-vim'

call plug#end()
