set nocompatible
set backspace=indent,eol,start
set autoindent
set spell spelllang=en_us
"set editing-mode vi
set clipboard=unnamed

set showmatch

filetype indent on
filetype plugin on

syntax enable

set number

" Python Support
autocmd Filetype python setlocal ts=4 sw=4 colorcolumn=80
set tabstop=4
set expandtab
let python_highlight_all=1

" Ini Support
autocmd Filetype dosini setlocal ts=4 sw=4 

" Javascript and Typescript support
autocmd Filetype json setlocal ts=2 sw=2
autocmd Filetype javascript setlocal ts=2 sw=2 colorcolumn=120
autocmd Filetype Typescript setlocal ts=2 sw=2 sts=4 colorcolumn=120

" HTML Support
autocmd Filetype html setlocal ts=2 sw=2 colorcolumn=120

" Kotlin Support
autocmd Filetype kotlin setlocal ts=4 sw=4 colorcolumn=100

" RST
autocmd FileType rst setlocal expandtab sw=4 ts=4 colorcolumn=80

" Colorschemes
set background=dark

" Shift tab to detab
vnoremap <S-Tab> <<
vnoremap <Tab> >>
inoremap <S-Tab> hello 
"inoremap <S-Tab> <C-d>
        
" System clipboard

set clipboard=unnamed

" VIM in the Shell

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

" Code Folding

set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=2

" ALE settings

let g:airline#extensions#ale#enabled = 1
let g:ale_completion_enabled = 1
let g:ale_set_quickfix=1 
let g:ale_open_list=0
"let g:ale_open_list = 1

" Vim Airline

set laststatus=2

" NerdTree
let NERDTreeIgnore = ['\.pyc$', '\.swp$', '.git', '.idea', 'node_modules', '.cache', '.pants.d', '.pids', '.pytest_cache', '.DS_store', '.pants.workdir.file_lock', '.DS_Store']
:map <leader>n :NERDTree<enter>
let NERDTreeShowHidden = 1

" NerdTree Commentator

let g:NERDSpaceDelims = 1
let g:NERDCustomDelimiters = {'python': {'left': '#:'}}
:map <C-\> <Leader>c<space>

call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle'}
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tpope/vim-git'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'altercation/vim-colors-solarized'
Plug 'vim-airline/vim-airline'
Plug 'jmcantrell/vim-virtualenv'
Plug 'Valloric/YouCompleteMe'
Plug 'nvie/vim-flake8'
Plug 'vim-scripts/indentpython.vim'
Plug 'Rykka/riv.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'pangloss/vim-javascript'
Plug 'leafgarland/typescript-vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'w0rp/ale'
Plug 'heavenshell/vim-pydocstring'
Plug 'pantsbuild/vim-pants'
Plug 'saltstack/salt-vim'
Plug 'stephpy/vim-yaml'
Plug 'jiangmiao/auto-pairs'
Plug 'mattn/emmet-vim'
Plug 'udalov/kotlin-vim'
Plug 'Yggdroot/indentLine'

call plug#end()
