#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export WORKON_HOME=$HOME/.virtualenvs
export ANDROID_HOME=/usr/local/opt/android-sdk
export FLASK_APP=run.py
export FLASK_DEBUG=1
export PROJECT_HOME=$HOME/workspace
export PATH="$HOME/.fastlane/bin:$PATH"
source /usr/local/bin/virtualenvwrapper_lazy.sh

#nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

###-tns-completion-start-###
if [ -f /Users/tamasiaina/.tnsrc ]; then 
    source /Users/tamasiaina/.tnsrc 
fi
###-tns-completion-end-###

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/tamasiaina/.sdkman"
[[ -s "/Users/tamasiaina/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/tamasiaina/.sdkman/bin/sdkman-init.sh"
